package utility;

public enum Screens {
    HOME_SCREEN,
    ARMOR_SCREEN,
    WEAPON_SCREEN,
    BOSS_SCREEN,
    CHARACTER_SCREEN,
    SORCERY_SCREEN,
    INCANTATION_SCREEN,
    COMMENT_SCREEN,
    SCREEN
}
